version: '3'

volumes:
  pg_data_kittygram:
  kittygram_static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_kittygram:/var/lib/postgresql/data
  backend:
    image: nurik878/kittygram_backend
    env_file: .env
    volumes:
      - kittygram_static:/backend_static
      - media:/media
    depends_on:
      - db
  frontend:
    image: nurik878/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - kittygram_static:/frontend_static
  gateway:
    image: nurik878/kittygram_gateway
    env_file: .env
    volumes:
      - kittygram_static:/static
      - media:/media
    ports:
      - 9000:80